// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSw_tn5uXgF_9KaB3a1n8a95gKNrX9caQ',
    appId: '1:84397369437:web:0ee533dd59939fbdb8c5b4',
    messagingSenderId: '84397369437',
    projectId: 'unico-connect-14548',
    authDomain: 'unico-connect-14548.firebaseapp.com',
    storageBucket: 'unico-connect-14548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGT1NrqF8iL44GpkcTIHCkAVYgnjGEESQ',
    appId: '1:84397369437:android:c74418f15c4a627eb8c5b4',
    messagingSenderId: '84397369437',
    projectId: 'unico-connect-14548',
    storageBucket: 'unico-connect-14548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9sGpEU8yxEbDjstb0NTg_rzYmLpgUnJ8',
    appId: '1:84397369437:ios:37b37f2772f494c8b8c5b4',
    messagingSenderId: '84397369437',
    projectId: 'unico-connect-14548',
    storageBucket: 'unico-connect-14548.appspot.com',
    iosBundleId: 'com.example.unicoConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9sGpEU8yxEbDjstb0NTg_rzYmLpgUnJ8',
    appId: '1:84397369437:ios:2ba70e0fe496ee6bb8c5b4',
    messagingSenderId: '84397369437',
    projectId: 'unico-connect-14548',
    storageBucket: 'unico-connect-14548.appspot.com',
    iosBundleId: 'com.example.unicoConnect.RunnerTests',
  );
}
